# Generated by Django 4.0.1 on 2022-01-06 02:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=20, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Рубрика',
                'verbose_name_plural': 'Рубрики',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=300, null=True, verbose_name='Заголовок')),
                ('content', models.TextField(null=True, verbose_name='Содержание')),
                ('published', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время публикации')),
                ('author', models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='post', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('rubric', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='post', to='book.rubric', verbose_name='Рубрика')),
            ],
        ),
    ]
