# Generated by Django 4.0.1 on 2022-01-06 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='last name')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='phone number')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='birthday')),
                ('is_active', models.BooleanField(default=True, help_text='Определяет, следует ли считать этого пользователя активным.Снимите этот флажок вместо удаления учетных записей.', verbose_name='active')),
                ('is_staff', models.BooleanField(default=False, help_text='Определяет, может ли пользователь войти как администратор.', verbose_name='staff status')),
                ('is_admin', models.BooleanField(default=False, help_text='Определяет, может ли пользователь войти как суперюзер.', verbose_name='superuser status')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
